-- Quant signal persistence.
-- Records every signal generated by quantitative strategies (flow, cross-market,
-- mean reversion, resolution proximity) along with execution status.
-- Used for P&L attribution, strategy performance tracking, and audit.

CREATE TABLE IF NOT EXISTS quant_signals (
    id                UUID NOT NULL DEFAULT gen_random_uuid(),
    kind              TEXT NOT NULL,           -- flow, cross_market, mean_reversion, resolution_proximity
    condition_id      TEXT NOT NULL,
    direction         TEXT NOT NULL,           -- buy_yes, buy_no
    confidence        DOUBLE PRECISION NOT NULL,
    size_usd          DECIMAL(20, 10),
    metadata          JSONB DEFAULT '{}',
    generated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    execution_status  TEXT DEFAULT 'pending',  -- pending, executed, skipped, failed
    skip_reason       TEXT,
    position_id       UUID REFERENCES positions(id),
    -- TimescaleDB requires partition column in all unique constraints
    PRIMARY KEY (id, generated_at)
);

-- Convert to TimescaleDB hypertable for time-series queries
SELECT create_hypertable(
    'quant_signals',
    'generated_at',
    chunk_time_interval => INTERVAL '1 day',
    if_not_exists => TRUE
);

-- Enable compression for older data
ALTER TABLE quant_signals SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'kind'
);

SELECT add_compression_policy('quant_signals', INTERVAL '7 days', if_not_exists => TRUE);

-- Retain 180 days of signal history
SELECT add_retention_policy('quant_signals', INTERVAL '180 days', if_not_exists => TRUE);

-- Query: recent signals by kind
CREATE INDEX IF NOT EXISTS idx_quant_signals_kind_time
    ON quant_signals (kind, generated_at DESC);

-- Query: signals for a specific market
CREATE INDEX IF NOT EXISTS idx_quant_signals_condition
    ON quant_signals (condition_id, generated_at DESC);

-- Query: executed signals (for P&L attribution)
CREATE INDEX IF NOT EXISTS idx_quant_signals_executed
    ON quant_signals (execution_status, generated_at DESC)
    WHERE execution_status = 'executed';
